/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.survey;
import javax.swing.*;
import java.awt.*;
import java.util.Map;

/**
 *
 * @author Sekwa
 */
public class ResultsPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ResultsPage.class.getName());

    /**
     * Creates new form ResultsPage
     */
    public ResultsPage() {
        initComponents();
        
        Map<String, Object> stats = DatabaseHelper.getSurveyStatistics();

        if (stats.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No survey data available yet.");
            return;
        }

        totalSurveysLabel.setText("Total number of surveys: " + stats.get("total"));
        averageAgeLabel.setText("Average age: " + String.format("%.1f", stats.get("average_age")));
        youngestLabel.setText("Youngest person who participated in survey: " + stats.get("youngest"));
        oldestLabel.setText("Oldest person who participated in survey: " + stats.get("oldest"));

        moviesAvgLabel.setText("People who like to watch movies: " + String.format("%.2f", stats.get("avg_movie")));
        radioAvgLabel.setText("People who like to listen to radio: " + String.format("%.2f", stats.get("avg_radio")));
        eatOutAvgLabel.setText("People who like to eat out: " + String.format("%.2f", stats.get("avg_eatout")));
        tvAvgLabel.setText("People who like to watch TV: " + String.format("%.2f", stats.get("avg_tv")));

        pizzaPercentLabel.setText("Percentage of people who like Pizza: " + String.format("%.1f%%", stats.get("percent_pizza")));
        pastaPercentLabel.setText("Percentage of people who like Pasta: " + String.format("%.1f%%", stats.get("percent_pasta")));
        papWorsPercentLabel.setText("Percentage of people who like Pap and Wors: " + String.format("%.1f%%", stats.get("percent_papwors")));

    }
    
    public void setTotalSurveys(int count) {
        totalSurveysLabel.setText("Total number of surveys: " + count);
    }

    public void setAverageAge(double age) {
        averageAgeLabel.setText("Average age: " + String.format("%.2f", age));
    }

    public void setOldestAge(int age) {
        oldestLabel.setText("Oldest person who participated in survey: " + age);
    }

    public void setYoungestAge(int age) {
        youngestLabel.setText("Youngest person who participated in survey: " + age);
    }

    public void setPizzaPercent(double percent) {
        pizzaPercentLabel.setText("Percentage of people who like Pizza: " + String.format("%.1f%%", percent));
    }

    public void setPastaPercent(double percent) {
        pastaPercentLabel.setText("Percentage of people who like Pasta: " + String.format("%.1f%%", percent));
    }

    public void setPapAndWorsPercent(double percent) {
        papWorsPercentLabel.setText("Percentage of people who like Pap and Wors: " + String.format("%.1f%%", percent));
    }

    public void setMoviesAvg(double rating) {
        moviesAvgLabel.setText("People who like to watch movies: " + String.format("%.2f", rating));
    }

    public void setRadioAvg(double rating) {
        radioAvgLabel.setText("People who like to listen to radio: " + String.format("%.2f", rating));
    }   

    public void setEatOutAvg(double rating) {
        eatOutAvgLabel.setText("People who like to eat out: " + String.format("%.2f", rating));
    }

    public void setTvAvg(double rating) {
        tvAvgLabel.setText("People who like to watch TV: " + String.format("%.2f", rating));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        totalSurveysLabel = new javax.swing.JLabel();
        averageAgeLabel = new javax.swing.JLabel();
        youngestLabel = new javax.swing.JLabel();
        oldestLabel = new javax.swing.JLabel();
        moviesAvgLabel = new javax.swing.JLabel();
        papWorsPercentLabel = new javax.swing.JLabel();
        pastaPercentLabel = new javax.swing.JLabel();
        pizzaPercentLabel = new javax.swing.JLabel();
        tvAvgLabel = new javax.swing.JLabel();
        eatOutAvgLabel = new javax.swing.JLabel();
        radioAvgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Survey Results");

        totalSurveysLabel.setText("Total number of surveys:");

        averageAgeLabel.setText("Average age:");

        youngestLabel.setText("Youngest person who participated in survey:");

        oldestLabel.setText("Oldest person who participated in survey:");

        moviesAvgLabel.setText("People who like to watch movies:");

        papWorsPercentLabel.setText("Percentage of people who like Pap and Wors:");

        pastaPercentLabel.setText("Percentage of people who like Pasta:");

        pizzaPercentLabel.setText("Percentage of people who like Pizza:");

        tvAvgLabel.setText("People who like to watch TV:");

        eatOutAvgLabel.setText("People who like to eat out:");

        radioAvgLabel.setText("People who like to listen to radio:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(441, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(429, 429, 429))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalSurveysLabel)
                            .addComponent(averageAgeLabel)
                            .addComponent(youngestLabel)
                            .addComponent(oldestLabel)
                            .addComponent(tvAvgLabel)
                            .addComponent(eatOutAvgLabel)
                            .addComponent(radioAvgLabel)
                            .addComponent(moviesAvgLabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(papWorsPercentLabel)
                            .addComponent(pastaPercentLabel)
                            .addComponent(pizzaPercentLabel))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(totalSurveysLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(averageAgeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(oldestLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(youngestLabel)
                .addGap(36, 36, 36)
                .addComponent(pizzaPercentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pastaPercentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(papWorsPercentLabel)
                .addGap(48, 48, 48)
                .addComponent(moviesAvgLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioAvgLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eatOutAvgLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tvAvgLabel)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ResultsPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel averageAgeLabel;
    private javax.swing.JLabel eatOutAvgLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel moviesAvgLabel;
    private javax.swing.JLabel oldestLabel;
    private javax.swing.JLabel papWorsPercentLabel;
    private javax.swing.JLabel pastaPercentLabel;
    private javax.swing.JLabel pizzaPercentLabel;
    private javax.swing.JLabel radioAvgLabel;
    private javax.swing.JLabel totalSurveysLabel;
    private javax.swing.JLabel tvAvgLabel;
    private javax.swing.JLabel youngestLabel;
    // End of variables declaration//GEN-END:variables
}
